apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  replicas: 8
  template:
    spec:
      containers:
      - name: frontend
        volumeMounts:
        - name: logs-cephfs
          mountPath: /data/srv/logs/frontend
        - name: logs-cephfs
          persistentVolumeClaim:
            claimName: logs-cephfs-claim-prod-default

