apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dbs2go-server
  name: dbs2go-server
  namespace: dbs
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: dbs2go-server
      volumeMounts:
      - name: logs
        mountPath: /data/logs

      - name: dbs2go-filebeat
        # side-car image to run filebeat and scrape dbs2go logs
      image: docker.elastic.co/beats/filebeat:7.12.0
      args: ["-c", "/etc/filebeat.yml", "-e"]
      env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
    volumeMounts:
    - name: logs
      mountPath: /data/logs
    - name: config
      mountPath: /etc/filebeat.yml
      readOnly: true
      subPath: filebeat.yml
    - name: data
      mountPath: /usr/share/filebeat/data
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
    - name: logs
      persistentVolumeClaim:
      claimName: logs-cephfs-claim-preprod-dbs
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
    - name: config
      configMap:
        defaultMode: 0640
        name: dbs2go-filebeat-config
    - name: data
      emptyDir: {}
