apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dmwmmon
  name: dmwmmon
  namespace: dmwm
spec:
  template:
    spec:
      containers:
      - name: dmwmmon
        volumeMounts:
          - name: logs-cephfs
            mountPath: /data/srv/logs/dmwmmon
          - name: logs-cephfs
            persistentVolumeClaim:
              claimName: logs-cephfs-claim-preprod-dmwm