apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: t0reqmon
  name: t0reqmon
  namespace: dmwm
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: t0reqmon
    resources:
      requests:
        memory: "3Gi"
        cpu: "1"
      limits:
        memory: "8Gi"
        cpu: "2"
    volumeMounts:
    - name: logs
      mountPath: /data/srv/logs/t0_reqmon
    - name: t0reqmon-filebeat
      image: docker.elastic.co/beats/filebeat:7.12.0
      args: ["-c", "/etc/filebeat.yml", "-e"]
      env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m"
      volumeMounts:
      - name: logs
        mountPath: /data/srv/logs/t0_reqmon
      - name: config
        mountPath: /etc/filebeat.yml
        readOnly: true
        subPath: filebeat.yml
      - name: data
        mountPath: /usr/share/filebeat/data
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
        securityContext:
        allowPrivilegeEscalation: false

      - name: logs
        persistentVolumeClaim:
          claimName: logs-cephfs-claim-preprod-dmwm
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          defaultMode: 0640
          name: t0reqmon-filebeat-config
      - name: data
        emptyDir: {}
