apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: t0wmadatasvc
  name: t0wmadatasvc
  namespace: tzero
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: t0wmadatasvc
    resources:
      requests:
        memory: "256Mi"
        cpu: "50m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
    volumeMounts:
    - name: logs
      mountPath: /data/srv/logs/t0wmadatasvc
    - name: t0wmadatasvc-filebeat
  image: docker.elastic.co/beats/filebeat:7.12.0
  args: ["-c", "/etc/filebeat.yml", "-e"]
  env:
  - name: MY_POD_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.name
  resources:
    requests:
      memory: "50Mi"
      cpu: "50m"
  volumeMounts:
  - name: logs
    mountPath: /data/srv/logs/t0wmadatasvc
  - name: config
    mountPath: /etc/filebeat.yml
    readOnly: true
    subPath: filebeat.yml
  - name: data
    mountPath: /usr/share/filebeat/data
  - name: varlog
    mountPath: /var/log
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
    securityContext:
      allowPrivilegeEscalation: false

  - name: logs
    persistentVolumeClaim:
      claimName: logs-cephfs-claim-preprod-tzero
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: config
    configMap:
      defaultMode: 0640
      name: t0wmadatasvc-filebeat-config
  - name: data
    emptyDir: {}
